### ISSUE TITLE
HGVS relationship between the transcript and the associated amino acid.

### ISSUE THREAD

**Issue by gemaroldan** [ga4gh-beacon/specification-v2#59]
The current "2.0.0-draft.3" version, in the /g_variants service, when implementing VariantAnnotation, using the following scheme "https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/draft.3/default_variant_annotations_schema.yaml#/components/schemas/VariantAnnotation", in the properties related to transcripts: HGVS is listed, but I do not see the relationship between the transcript and the associated amino acid. Wouldn't it be interesting to cross this information in some way?

    ...
    "variantAnnotations": {
          "variantId": "rs1049206",
          "variantAlternativeId": null,
          "genomicHGVSId": "NC_000016.9:g.4935145_4935146insT",
          "transcriptHGVSId": [
            "ENST00000345988.2:c.3510G>A",
            "NM_002705.5:c.3510G>A",
            "ENST00000590782.2:c.3504G>A",
            "ENST00000592772.1:c.1773G>A"
          ],
          "proteinHGVSIds": [
            "ENSP00000340510.2:p.Val1170=",
            "NP_002696.4:p.Val1170=",
            "ENSP00000465640.1:p.Val1168=",
            "ENSP00000467699.1:p.Val591="
          ],
          "molecularConsequence": null,
          "aminoacidChange": [
            "VAL1170>VAL",
            "VAL1168>VAL",
            "VAL591>VAL"
          ],
         ...

For example:
![image](https://user-images.githubusercontent.com/9883342/116206560-38a44500-a73f-11eb-99b3-9ac4c22acc02.png)

**Comment by jrambla** [comment]
Moved/referenced to the Beacon v2 Models repo issue#2 https://github.com/ga4gh-beacon/beacon-v2-Models/issues/2

**Comment by clauw87** [comment]
If I understand right, this is about keeping the correspondence between transcriptHGVSId - proteinHGVSIds -molecularConsequence -  aminoacidChange instead of just listing them in the corresponding order, leaving possibly a NA in place when not applicable (?). If so, this then maybe could be solved then with a list of objects instead of lists of each variable separately, where each element of the list represent each transcript and will include each of this elements, NA for those not applicable (e.g leaving for aminoacidChange NA for transcripts that are non-coding, e.g having genomicFeatures class set as non-coding RNA). Would this work?

**Comment by jrambla** [comment]
@gemaroldan could you look at the issue in https://github.com/ga4gh-beacon/beacon-v2-Models/issues/2 ?
