### ISSUE TITLE
dynamic response endpoint

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/specification-v2#69]
Currently there are 32 endpoints for beacon, this seems like a large number when the query body for most of these endpoints is identical.

I propose that instead of querying a certain endpoint to receive certain responses you can instead include a "responseFormat" parameter with the request body and query a generic endpoint, such as /query. The response format can be simple, such as "variants" or "biosamples" but it could also be greatly expanded to provide a method of returning more complex response objects, such as "individuals=>[biosamples,variants]" where the query is applied to the left most object. This would be interpreted as "for every individual matching the query request return information about the individual as well as all biosamples and variants related to said individual"

This can become even more complex by incorporating multiple queries which act on different response objects, such as:

"individuals:queryA=>biosamples=>variants:queryB"

In this scenario the request body is actually comprised of two different queries, A and B. Query A describes individuals that the user is interested in, all biosamples relating to matching individuals are also returned and then for each biosample any variants which match queryB are also returned.

This complex query functionality is already available to beacon users, but they would need to perform many different queries to gather all of the information and then manually combine it. Combining the queries in this way would be a powerful tool for users and it would likely be quicker and computationally cheaper for beacon owners to complete a complex query than potentially 100's or 1000's or smaller queries, both of which would return the same data in the end.

**Comment by mbaudis** [comment]
Just FYI, we follow this concept in having both `responseFormat` and `responseType` as optional parameters, e.g. to shape non-standard responses.

However, for the use case above we just have handovers. E.g. each variant query has a set of handovers, for retrieving all biosamples, individuals ... etc.

We had previous discussions (esp. w/ @jrambla ) in which I've argued some of your points but with handovers as solution instead of the zoo of paths. But I made my peace & offer both - the handovers are just always there since our query stack delivers all matches through the variants - analyses - biosamples - individuals ... object stack.

For aggregation (not part of Beacon yet) we just have a temporary pointer to previously matched results and aggregate new request with those.

Back to the issue: For me not compelling enough, or too complex, right now. But YMMV.

**Comment by jrambla** [comment]
The current plan is to bring Beacon v2 as more directed queries and responses and get feedback from a broad of adopters (or non-adopters if the model doesn't fit their needs) and evolve it to a more open approach if that is what is requested by a majority.
The expectation of 'easy to use' and 'easy to implement' became quite restrictive if non-experienced implementers should be taken into account.
